### ISSUE TITLE
你好,我按步骤尝试还是无法登录啊，不知道你遇到过没有

### ISSUE THREAD

**Issue by trey03** [sunweisheng/Kubernetes#1]
![image](https://user-images.githubusercontent.com/8022014/68122607-b110b800-ff45-11e9-99c7-838ecc746dac.png)

**Comment by sunweisheng** [comment]
首先密钥找对了吗？其次密钥复制完整了吗？

**Comment by sunweisheng** [comment]
首选密钥是服务账号的密码，其次密码前面的空格不能要
